server:
  port: 80
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://222.200.180.59:3306/bpm-workflow-1?characterEncoding=utf8&useSSL=false
    username: root
    password: workflow
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

